### ISSUE TITLE
What constraints should be applied to "pre-filled" columns

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/submission-schema#115]
Look though the submission schema for the comment "Do not edit these values. A template will be provided by NMDC in which these values have been pre-filled."

- dna_project_contact
- dna_samp_id
- dna_seq_project
- dna_seq_project_name
- dna_seq_project_pi
- proposal_dna
- proposal_rna
- rna_project_contact
- rna_samp_id
- rna_seq_project
- rna_seq_project_name
- rna_seq_project_pi

CC @brynnz22 @mslarae13

**Comment by mslarae13** [comment]
@turbomam I think we can close this. It's OBE.
The fields have been locked & the information, for now, is provided by me. And in the future will come from the API.
