### ISSUE TITLE
just set nmdc-schema import tag to `main` for now

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/submission-schema#121]

**Comment by mslarae13** [comment]
Relates to #131  ?

@turbomam

**Comment by mslarae13** [comment]
this would undo setting the tagged release.

Do we want to import "main" branch or tag release? Tagged release are better. Closing as OBE.

**Comment by turbomam** [comment]
Boy, I'm having a hard time remembering what I meant by this issue. It makes sense to me that @mslarae13 closed it.

What does OBE mean?

**Comment by turbomam** [comment]
https://community.atlassian.com/t5/Jira-questions/What-does-OBE-Overcome-By-Events-test-execution-status-actually/qaq-p/1288005 ?
