### ISSUE TITLE
tube/plate/well validation rules are not working

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/submission-schema#127]
examples have been moved to the unexpected_pass directory

I think this was working at one point and I suspect that we can get it working agin

see also
- https://github.com/microbiomedata/nmdc-schema/issues/919

**Comment by mslarae13** [comment]
Regex for plate position not working.
the problem with the regex is that the negative lookahead needs to include the end-of-string marker as well. The correct regex is: ^(?!A1$|A12$|H1$|H12$)(([A-H][1-9])|([A-H]1[0-2]))$

A10 won't validate and B01 won't validate... B1 and B01 should be valid.

**Comment by mslarae13** [comment]
See submission c41dfeac-102e-43b2-adae-6a67f25791f0 for an example
@pkalita-lbl

**Comment by mslarae13** [comment]
@pkalita-lbl @turbomam 
Is this fixed in dev? So ingest to prod is still needed?

**Comment by pkalita-lbl** [comment]
> Is this fixed in dev?

I believe so but you should test and verify

> So ingest to prod is still needed?

Not sure what ingest has anything to do with it? You mean deploy to production? If so, yes, whatever is on dev will go to production with the next release. It's not an change-by-change thing.

**Comment by mslarae13** [comment]
Resolved and in prod with most recent ingest.
