### ISSUE TITLE
Sample Data for EmslInterface

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/submission-schema#129]
Create sample data files for EmslInterface files.

**Comment by brynnz22** [comment]
@turbomam  Yep I am checking! I am just adding to what you have for the invalid data.

**Comment by mslarae13** [comment]
@brynnz22 is this still relevant / needs done? I can't totally tell from Mark's comment if this was completed from the PR, or if there's still work to do

**Comment by brynnz22** [comment]
I think we can close this. I worked on this a long time ago.
