### ISSUE TITLE
nmdc-schema 7.6.0 -> 7.6.2

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/submission-schema#131]

**Comment by mslarae13** [comment]
@turbomam is schema still on 7.6.2? I assume this is to migrate the submission schema to reference the correct schema version?

**Comment by mslarae13** [comment]
this is done. see https://github.com/microbiomedata/submission-schema/blob/main/sheets_and_friends/tsv_in/import_slots_regardless.tsv

10.2 is current
