### ISSUE TITLE
Add Sample Data for Soil Interface

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/submission-schema#133]
Add additional sample data files for SoilInterace

**Comment by mslarae13** [comment]
@brynnz22  sample data == example data
?

**Comment by brynnz22** [comment]
@mslarae13 yes! example data. I'm slowly working through them!

**Comment by mslarae13** [comment]
@brynnz22 
Do you mind if anyone else joins this effort?

**Comment by brynnz22** [comment]
No, I haven't had time. Whoever wants to take over, please!

**Comment by bmeluch** [comment]
This is completed, several valid and invalid `soil_data` example files exist in https://github.com/microbiomedata/submission-schema/tree/main/src/data.
