### ISSUE TITLE
update description for lat_lon in the submission schema package interfaces

### ISSUE THREAD

**Issue by aclum** [microbiomedata/submission-schema#140]
For [Class SoilInterface](https://microbiomedata.github.io/submission-schema/SoilInterface) the description appears to be more of a note than an actual description.
soil
  lat_lon:
    name: lat_lon
    description: This is currently a required field but it's not clear if this should
      be required for human hosts

 Please update soil dh interface and other dh interface packages to use the lat_lon [global definition](https://microbiomedata.github.io/submission-schema/lat_lon/).
description: The geographical origin of the sample as defined by latitude and longitude.
  The values should be reported in decimal degrees and in WGS84 system
![Screenshot 2023-07-17 at 4 53 21 PM](https://github.com/microbiomedata/submission-schema/assets/8196591/b3ffa2b5-e18e-43d3-8bc4-4e41c4a46b70)

cc @mslarae13

**Comment by mslarae13** [comment]
That's a bug!! That should be the note.. not the description. @pkalita-lbl  can you take a look?

**Comment by ssarrafan** [comment]
@mslarae13 is this still a priority issue?

**Comment by mslarae13** [comment]
@aclum yes, this definitely need fixed. @brynnz22  or @pkalita-lbl  can either of you help with this?

**Comment by pkalita-lbl** [comment]
These changes were released in `nmdc-schema@8.1.0`. They have also been imported into `submission-schema@8.1.1` which is based on `nmdc-schema@8.1.0`. Currently awaiting review to bring `submission-schema@8.1.1` into `nmdc-server`: https://github.com/microbiomedata/nmdc-server/pull/1062

**Comment by pkalita-lbl** [comment]
Closing this since there is not development work left to do
