### ISSUE TITLE
"soil horizon method" appears in submission portal for water samples

### ISSUE THREAD

**Issue by bmeluch** [microbiomedata/submission-schema#148]
![image](https://github.com/microbiomedata/submission-schema/assets/107661103/7dc2fac5-0db1-4f5d-9ac1-d087d18b6531)

**Comment by bmeluch** [comment]
"horizon method" also appears in submission portal when using "miscellaneous natural or artificial environment" package, but "horizon" does not

**Comment by mslarae13** [comment]
@bmeluch let's look at this thursday. I think we can fix this easily. 

Can you just double check that this issues does also exist in MIxS: https://github.com/GenomicsStandardsConsortium/mixs/tree/main/mixs/excel 

Look at the water file & make sure these terms aren't listed there.

**Comment by bmeluch** [comment]
Double checked the MIxS excel files, "horizon" doesn't appear anywhere in "misc natural or artificial environment" or in "water"
