### ISSUE TITLE
Generate submission schema from specific version of main schema

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/submission-schema#15]
Currently the `sheets_and_friends/tsv_in/sheets-for-nmdc-submission-schema_import_slots_regardless.tsv` file specifies that certain slots are imported into the submission schema from the main schema using its latest commit to `main`. I think this is not ideal.
* For a given version of the submission schema, if I want to know which version of the main schema it was built from (and therefore is compatible with) I can only do so by looking at the date and time that the submission schema was generated and comparing it to the date and times of commits to the `main` branch of the main schema. There's no guarantee that the commit of the main schema corresponds to any particular released version of the main schema (it may be between releases or ahead of the latest release).
* The build of the submission schema is not necessarily reproducible. I can `make src/submission_schema/schema/submission_schema.yaml`, change nothing in the submission schema, run the same make command again and possibly get different results because of a new commit to the main schema repo. Or, if I had made changes within the submission schema repo it makes it hard to assess which changes in `src/submission_schema/schema/submission_schema.yaml` were the result of my changes and which were the result of the upstream changes.

I propose we pin the slot imports to a release tag of the main schema. To make experimental changes in a branch of the submission schema that pin can be changed to a branch or commit in the main schema during development. But before those submission schema changes can be merged back into `main` the pin should be to a (possibly new) release tag of the main schema.

**Comment by turbomam** [comment]
I'm making some changes to the ways modification are applied. That shouldn't overlap with what you are suggesting.
