### ISSUE TITLE
depth should not be required for host-associated

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/submission-schema#150]
NMDC submission schema requires depth for host-associated. this should be optional

- [ ] check and update NMDC schema
- [ ] confirm requirement level update in NMDC submission schema
- [ ] push to dev and test
- [ ] push to prod and test

relates to https://github.com/microbiomedata/nmdc-schema/issues/612

**Comment by bmeluch** [comment]
As far as I can tell, `depth` is not required in the NMDC schema, so this only needs to be a submission schema change to make `depth` required for the appropriate sample types.
