### ISSUE TITLE
Create submission-schema using Berkeley-schema

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/submission-schema#220]
NMDC berkeley-schema should be tested with nmdc submission-schema creation. 

We have a berkeley submission portal environment. 
Make a berkeley fork of the submission schema
Build the submission schema off the berkeley RC
Make a submission-schema RC
Plug it in to the berkeley instance of the submission portal
Test

**Comment by mslarae13** [comment]
Discussed at 08/28 1pm metadata meeting
- @pkalita-lbl doesn't expect the type field to break anything

@eecavanna noted that the berkeley instance of the submission portal is currently glitched. So something is wrong..

**Comment by pkalita-lbl** [comment]
Here is the release candidate of `nmdc-submission-schema`, based on v11.0.0rc20 of `nmdc-schema`:

* https://pypi.org/project/nmdc-submission-schema/11.0.0rc1/

That version is now being used by https://data-berkeley.microbiomedata.org/. 

I did some brief testing there and didn't find anything that looked wrong. Sending over to Montana for additional testing. Montana, please feel free to close this issue if you think everything looks good.

**Comment by eecavanna** [comment]
Here's an update about:
> @eecavanna noted that the berkeley instance of the submission portal is currently glitched. So something is wrong

Specifically, at that time, I was able to see the list of my submissions on the "Home" stage; but was not able to proceed through the subsequent stages. When I proceeded to the "Submission Context" stage, the page (under the stage bar) was blank instead of showing a form.

Now, the page (under the stage bar) is no longer blank, and I do see a form. The non-blank-ness is shown below.

![image](https://github.com/user-attachments/assets/90ebfaa3-a115-47fe-bfd3-24c6574ec283)

**Comment by pkalita-lbl** [comment]
Ah, that's what I fixed in https://github.com/microbiomedata/nmdc-server/pull/1375

**Comment by mslarae13** [comment]
@pkalita-lbl  

Made new issues for bugs I found: (testing in progress)
- https://github.com/microbiomedata/submission-schema/issues/225

**Comment by bmeluch** [comment]
My viewer and editor permissions are working!

**Comment by JamesTessmer** [comment]
I can't see any submissions on berkeley-dev that I was given access to. I do see that same bug appearing for another submission I had back from February though.

**Comment by brynnz22** [comment]
I am not seeing any submissions either, but I'm not sure which submission link I should be using?

**Comment by mslarae13** [comment]
@brynnz22 @JamesTessmer 

https://data-berkeley.microbiomedata.org/submission/home

Hopefully I got your ORCIDs right?

**Comment by mslarae13** [comment]
yup. it's right.

**Comment by ssarrafan** [comment]
@mslarae13 since you're out tomorrow, can this issue be moved/closed today?

**Comment by mslarae13** [comment]
closed, no, there's a bug.

Check with @pkalita-lbl if it should be next sprint or delayed

**Comment by ssarrafan** [comment]
> closed, no, there's a bug.
> 
> Check with @pkalita-lbl if it should be next sprint or delayed

Isn't the bug part of another issue?  https://github.com/microbiomedata/submission-schema/issues/225 Or is there a second bug that should be in this issue?

**Comment by brynnz22** [comment]
@mslarae13  I was able to see the submissions, but it says I don't have permission to edit the page for either of the two submissions.

**Comment by pkalita-lbl** [comment]
* https://github.com/microbiomedata/submission-schema/issues/225 has nothing to do with the Berkeley schema whatsoever. 
* I'm not quite sure I'm following what issues people are having with permissions, but that also would have nothing to do with the Berkeley schema.

I think this one has run its course. Closing.
