### ISSUE TITLE
Review NMDC submission schema for berkeley-schema needed changes

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/submission-schema#221]
Dependent on https://github.com/microbiomedata/submission-schema/issues/220 

Once the instance has been set up and the berkeley-schema name submission-schema is live, make the changes we might need.

**Comment by pkalita-lbl** [comment]
Do we need any changes? Can we close this?

**Comment by mslarae13** [comment]
If no changes are needed, and everything is working. Yup! We can close it! 
Looks like https://github.com/microbiomedata/nmdc-server/issues/1377 was resolved!
