### ISSUE TITLE
Resolve `DhMultiviewCommonColumns` naming issue

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/submission-schema#24]
Some sheets use `DhMultiviewCommonColumns` and others use `DhMultiviewCommonColumnsMixin`. We should pick one and make sure it's used consistently everywhere.

**Comment by turbomam** [comment]
`DhMultiviewCommonColumnsMixin` does't appear anywhere in my https://github.com/microbiomedata/submission-schema/tree/issue-18-water-patterns! But I don't care which you pick.

**Comment by pkalita-lbl** [comment]
So should I hold off on making this change? Or?

**Comment by turbomam** [comment]
No, go ahead with whatever you think is best and I will follow your example in my Water Patterns branch.
