### ISSUE TITLE
JgiMg and JgiMt: Add rule that requires a dna_cont_well when the dna_cont_type is "plate"

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/submission-schema#59]
But not vice versa

**Comment by turbomam** [comment]
try a simpler rule first? 

- when the dna_cont_type= plate, then the dna_volume must be less than 1 (mL?)
- when the dna_cont_type = plate, then the dna_volume must be greater than 1

**Comment by turbomam** [comment]
```json
[{"preconditions":{"slot_conditions":{"dna_cont_type":{"equals_string":"plate"}}},"postconditions":{"slot_conditions":{"dna_volume":{"maximum_value":1}}}},{"preconditions":{"slot_conditions":{"dna_cont_type":{"equals_string":"tube"}}},"postconditions":{"slot_conditions":{"dna_volume":{"minimum_value":1}}}}]
```

**Comment by turbomam** [comment]
@pkalita-lbl will be working on the emission of rules by gen-jsonschema

**Comment by mslarae13** [comment]
Duplicate https://github.com/microbiomedata/nmdc-schema/issues/1433

Closing in favor of the issue that includes DNA/RNA plate and other slot dependancies.
