### ISSUE TITLE
start making plant associated sample data

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/submission-schema#99]
- [ ] minimal valid example inside of a SampleData (see [usage](https://microbiomedata.github.io/submission-schema/PlantAssociatedInterface/#usages)) 
- [ ] use that minimal valid as a starting point for a single-error invalid file

**Comment by turbomam** [comment]
We need to discuss which other DhInterfaces we are going to provide example data for. Those should each have separate issues.

@mslarae13 will have good input for prioritizing

**Comment by brynnz22** [comment]
@mslarae13 mentioned to make example data for `SoilInterface`, `EMSLInterface`, `JGIMgInterface` and `JGIMInterface` and do plant, sediment, and water next. I will start new issues for these.

**Comment by mslarae13** [comment]
@brynnz22 are you actively working on this? Or just as you have time?

**Comment by brynnz22** [comment]
No, I have not been actively working on this! Happy to let Bea take over if she'd like to!

**Comment by bmeluch** [comment]
This is completed, valid and invalid `plant_associated_data` example files exist.
https://github.com/microbiomedata/submission-schema/blob/main/src/data/valid/SampleData-plant-assoc-min.yaml
https://github.com/microbiomedata/submission-schema/blob/main/src/data/invalid/SampleData-plant-assoc--with-flavor.yaml
https://github.com/microbiomedata/submission-schema/blob/main/src/data/invalid/SampleData-plant-associated-illegally-high-lat.yaml
